stages:
  data_ingestion:
    cmd: python src/ChickenDiseaseClassifier/pipeline/stage01_data_ingestion.py
    deps:
      - src/ChickenDiseaseClassifier/pipeline/stage01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chicken-fecal-images


  prepare_base_model:
    cmd: python src/ChickenDiseaseClassifier/pipeline/stage02_base_model.py
    deps:
      - src/ChickenDiseaseClassifier/pipeline/stage02_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model



  training:
    cmd: python src/ChickenDiseaseClassifier/pipeline/stage03_training.py
    deps:
      - src/ChickenDiseaseClassifier/pipeline/stage03_training.py
      - src/ChickenDiseaseClassifier/components/callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.keras



  evaluation:
    cmd: python src/ChickenDiseaseClassifier/pipeline/stage04_evaluation.py
    deps:
      - src/ChickenDiseaseClassifier/pipeline/stage04_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/training/model.keras
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false