AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1 #INCREASE EPOCHS WITHIN 10-25 FOR BETTER RESULT
CLASSES: 7
WEIGHTS: imagenet
LEARNING_RATE: 0.01 #INCREASE LEARNING_RATE BY 0.001 OR 0.0001

